#!/usr/bin/python

import gi
gi.require_version('Gtk', '3.0')
gi.require_version('WebKit2', '4.0')

from gi.repository import Gtk
from gi.repository import WebKit2
import sys

# set default resolution 800x600
defaultxres = 800
defaultyres = 600

# check syntax
if len(sys.argv) < 2:
  print("Usage: sswb url [title]")
  sys.exit()

# check if title is passed from command line
if len(sys.argv) > 2:
  start = 2
  titolo = ""
  while (start < len(sys.argv)):
    titolo = titolo + str(sys.argv[start]) + " "
    start = start + 1
  titolo = titolo[:-1]
else:
  titolo = "Stupid Simply Web Browser"

# read url from commandline
url = str(sys.argv[1])
# check if url start with something:// else add http://
if url.find("://") <= 2:
  url = "https://" + url
  
if len(sys.argv) > 2:
	titolo = str(sys.argv[2])
  
class StupidSimplyWebBrowserWindow(Gtk.Window):
  
  def __init__(self, iltitolo, sizex, sizey):
    Gtk.Window.__init__(self, title=iltitolo)
    self.set_default_size(sizex, sizey)
    self.scroller = Gtk.ScrolledWindow()
    self.web = WebKit2.WebView()
    self.scroller.add(self.web)
    self.add(self.scroller)
      
  def goto(self, theurl):
    self.web.load_uri(theurl)
    
win = StupidSimplyWebBrowserWindow(titolo, defaultxres, defaultyres)
win.goto(url)
win.connect('delete-event', Gtk.main_quit)

win.show_all()
Gtk.main()
